### ISSUE TITLE
class_labels_indices.csv is missing

### ISSUE THREAD

**Issue by maxpatcher** [qiuqiangkong/audioset_tagging_cnn#1]
Hey guys!

Thanks for sharing the code, but running the inference, this error pops up:

Traceback (most recent call last):
  File "pytorch/inference_template.py", line 26, in <module>
    import config
  File "/Users/admin/Desktop/audioset_tagging_cnn/pytorch/../utils/config.py", line 8, in <module>
    with open('metadata/class_labels_indices.csv', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/class_labels_indices.csv'

Could you pls. add that file?

Thx a lot,
Max

**Comment by cantwbr** [comment]
Correct me if I'm wrong. But this file should contain the original class labels from the AudioSet dataset. This can be found [here](http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/class_labels_indices.csv).

**Comment by maxpatcher** [comment]
Hi, Thank you for answering. I found the file after some digging and yes this is the correct one.

Thanks again !
