### ISSUE TITLE
Change License to Reflect Proper Authors

### ISSUE THREAD

**Issue by seanytak** [qiuqiangkong/audioset_tagging_cnn#15]
Hello, I am interested in leveraging the great work you folks have done here. However, the current MIT License appears to just be a copy of the one used for the AngularJS project and thus doesn't reflect that the copyright holders are the authors of the associated paper "Qiuqiang Kong, Yin Cao, Turab Iqbal, Yuxuan Wang, Wenwu Wang, Mark D. Plumbley". Updating this to would be greatly appreciated!

**Comment by qiuqiangkong** [comment]
Hi seanytak, thanks for letting me know! The LICENSE.MIT has been updated!
