### ISSUE TITLE
The procedure

### ISSUE THREAD

**Issue by IcyHao** [qiuqiangkong/audioset_tagging_cnn#30]
Hi, I was confused about the procedure of the experiment although I had looked through the README.md. Could you list out the steps of the experiment? Thanks a lot.

**Comment by qiuqiangkong** [comment]
Hi, the easiest way is to download the pretrained models and try to inference an audio clip. This should be in the first part of the README.

**Comment by IcyHao** [comment]
Thanks for the clarification.  Inside the runme.sh file,  at the third line you define the workspace path. May I know what exactly it refers to? And also in the 43rd line of the same file, in the path of the audios_dir there is a file called "eval_segments". Are these refer to the audio clips?

**Comment by qiuqiangkong** [comment]
Hi, workspace is your local directory that will save checkpoints, etc.
eval_segments refer to evaluation audio clips.

**Comment by IcyHao** [comment]
When I try to download the evaluation wavs, I get the error saying "dataset.py download_wavs: error: the following arguments are required: --audios_dir".  As I already include the audios_dir in my code when executing, I got no idea how I got this error. Do you face this problem before>

Below is my code --
python3 d:/audioset_tagging_cnn-master/utils/dataset.py download_wavs --csv_path="./datasets/audioset201906""/metadata/eval_segments.csv" --audios_dir="./datasets/audioset201906""/audios/eval_segments"

**Comment by qiuqiangkong** [comment]
Hi, I did not have this problem. Did you use windows? Check if the dir of
of audios_dir is correct?

**Comment by IcyHao** [comment]
I use windows. I had checked that it is in the correct directory.
![Capture](https://user-images.githubusercontent.com/57998537/108332307-8d6b9280-71c7-11eb-816b-b81bdb42259a.JPG)

**Comment by qiuqiangkong** [comment]
I saw there is an "" in your path
"./datasets/audioset201906""/metadata/eval_segments.csv"?

**Comment by IcyHao** [comment]
Oh, it's my mistake. But then when I execute it, I got another error. Is this because the function cannot find the file?

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '_logs/download_dataset/D:'

**Comment by qiuqiangkong** [comment]
'_logs/download_dataset/D:' is not a good path. There can be a few path
issues on windows systems. I thought something like "D:/xxx/workspaces/"
would be better.

**Comment by IcyHao** [comment]
Inside the dataset.py, I found that there is a line that seems related to the error, is this what I need to change? But I had tried to change to '_logs/download_dataset/D:/audioset_tagging_cnn-master/{}' and it still gives me the same error.

logs_dir = '_logs/download_dataset/{}'.format(get_filename(csv_path))

![1](https://user-images.githubusercontent.com/57998537/108827686-d05da980-75bd-11eb-97b5-06b5fac196cd.JPG)

**Comment by qiuqiangkong** [comment]
Try to print *get_filename(csv_path)* and see what you got?

**Comment by IcyHao** [comment]
It shows D:\audioset_tagging_cnn-master\datasets\audioset201906\metadata\eval_segments

**Comment by IcyHao** [comment]
Ok, I got it. So after downloading the waves, I run the code of packing waveforms to the hdf5 file and it shows files do not exist. When I successfully download the evaluation wavs, I only got 10 files but the packing function is looking for 20000++ files. Is it because of I miss some steps or the download is not in the correct way?

[0006.log](https://github.com/qiuqiangkong/audioset_tagging_cnn/files/6039454/0006.log)

**Comment by qiuqiangkong** [comment]
Hi, check if the download is running correctly? Youtube is limiting the
number of videos to be downloaded recently.

**Comment by IcyHao** [comment]
These are the only thing that I got when I download the evaluation wavs. Are these things that you suppose to get when running the download?

![download](https://user-images.githubusercontent.com/57998537/109135643-3463a780-774f-11eb-918e-ac897b42c5cc.JPG)

**Comment by qiuqiangkong** [comment]
The downloading looks not successful. There should be 20k+ files downloaded.

**Comment by IcyHao** [comment]
Just a quick question, what is the point of the evaluation set?

**Comment by qiuqiangkong** [comment]
The evaluation set contains around ~20k audio clips for evaluating the
performance.

**Comment by IcyHao** [comment]
So it is not used for training and inferencing?

**Comment by qiuqiangkong** [comment]
No, eval is not for training.

**Comment by IcyHao** [comment]
Sorry for interrupting you again. I had downloaded the balanced training segments and I found that they are not converted to wav forms. So I delete them and redownload again, but now it can't run the code at line 101 and below. To run the code, the length of video_paths needs to bigger than zero but what I print out is an empty set in line 99 (The picture below is the output when I run the download_wavs command. Do you know what is going on?

![Capture](https://user-images.githubusercontent.com/57998537/111038560-9dbb0a00-8421-11eb-8ee2-e66aed049fca.PNG)

**Comment by qiuqiangkong** [comment]
Hi, have you checked if the videos are downloaded? If not, L101 will return
empty.

**Comment by IcyHao** [comment]
Hi again, the terminal had shown that it did not have enough RAM when I run the inference & training step. Other than reducing the training samples or the batch size, are there any ways that could reduce the usage of RAM?

**Comment by qiuqiangkong** [comment]
Hi, there are 3 ways to reduce RAM usage: 1) Reduce batch size, 2) Reduce
model size, 3) Use a larger RAM.

Best wishes,
Qiuqiang

**Comment by IcyHao** [comment]
Ok, thanks a lot.
