### ISSUE TITLE
First float32_to_int16, and then int16_to_float32?

### ISSUE THREAD

**Issue by sysuzyq** [qiuqiangkong/audioset_tagging_cnn#37]
during training, you transform the waveform from float32 to int16, and then back to float32.  could you tell me why ?

but in pytorch/inference.py , you don't  do this.  could you tell me why ?

**Comment by RicherMans** [comment]
He does that to save some space.
The raw data is ~ 1.1Tb, and by just this simple transformation, the datasize gets halved without much of a drawback.

**Comment by sysuzyq** [comment]
> He does that to save some space.
> The raw data is ~ 1.1Tb, and by just this simple transformation, the datasize gets halved without much of a drawback.

thanks
