### ISSUE TITLE
Coud not find file "unbalanced_train_segments_part38_partial.z01" in dataset

### ISSUE THREAD

**Issue by owlwang** [qiuqiangkong/audioset_tagging_cnn#44]
I am reproducing your paper recently.
But after downloading your dataset, I found that the dataset is missing this file. 

"**unbalanced_train_segments_part38_partial.z01**"

It seems that this file has not been uploaded. Could you please upload this missing file?

**Comment by JeffC0628** [comment]
same question， there is no _unbalanced_train_segments_part38_partial.z01_ file in baidu cloud .

**Comment by qiuqiangkong** [comment]
Hi all, part38 is uploaded now!
