### ISSUE TITLE
wav file not include in eval_segment.csv

### ISSUE THREAD

**Issue by AntroFyo** [qiuqiangkong/audioset_tagging_cnn#57]
hi, there is the problem i have met.After unzipping the eval_segments.zip file, i found many wav files are not included in eval_segments.csv. Like YzzbTaK7CZJY.wav. So i do not see the labels of these wavs. Could you provide the csvs you used when training. Thanks!

**Comment by one2ten** [comment]
@zdj97 I have the same problem. How did you solve it? Thanks!

**Comment by daisukelab** [comment]
If you find 90% or similar of what is listed in the eval_segments.csv, it would be as expected.
(I believe the eval_segments.csv you are referring to is the http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/eval_segments.csv)
As you know, YouTube videos disappear. Even the ones Dr Kong retrieved would have had some missing.

**Comment by one2ten** [comment]
@daisukelab  Thanks! :)

**Comment by AntroFyo** [comment]
> @zdj97 I have the same problem. How did you solve it? Thanks!
I found what caused this. The downloaded wav names like this Y-xxxx.wav, while the eval_segment.csv has wav names like this xxxx.wav. So, drop the Y ahead is Okay.
