### ISSUE TITLE
Transfer learning for a few classes

### ISSUE THREAD

**Issue by dopc** [qiuqiangkong/audioset_tagging_cnn#9]
Hey, thanks for the great work.

I want to fine-tune your pre-trained models for less classes than 527.
Can you please guide me?

I have run finetune_template.

`GPU number: 1
Load pretrained model successfully!
Process finished with exit code 0`

That's the only output.

Also tried to train from scratch with just 2 classes.
but I got several errors because of indexing.
I just followed runme.sh for training from scratch.

Thx

**Comment by qiuqiangkong** [comment]
Hi, have a look at this guide: https://github.com/qiuqiangkong/panns_transfer_to_gtzan

**Comment by dopc** [comment]
@qiuqiangkong thank you so much! I will look at it.
